import Head from 'next/head'
import Image from 'next/image'
import 'bootstarp/dist/bootstrap.min.css'
import 'bootstarp/dist/bootstrap.min.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Osama Sallam Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <button type="button" class="btn btn-success">

      </Head>
    </div>
  )
}
